version: '3.8'

services:
  postgres:
    build: .
    container_name: postgres-container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"   # Expose PostgreSQL on the host machine
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data

  # pgAdmin Service
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "80:80"  # Expose pgAdmin UI on port 80
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin # Persist pgAdmin data

volumes:
  postgres_data:
  pgadmin_data:
